curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Jennifer", "eventtype": "boughtCodingCourse", "specifics": {"platform":"Coursera", "price": "50$"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Chima", "eventtype": "subscribedToTV", "specifics": {"channel":"Disney", "for_month": "December"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Steve", "eventtype": "payingDues", "specifics": {"what":"light bills", "for_month": "June"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Jennifer", "eventtype": "boughtCodingCourse", "specifics": {"platform":"Coursera", "price": "50$"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Jennifer", "eventtype": "boughtCodingCourse", "specifics": {"platform":"Coursera", "price": "50$"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Chima", "eventtype": "subscribedToTV", "specifics": {"channel":"Disney", "for_month": "December"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Steve", "eventtype": "payingDues", "specifics": {"what":"light bills", "for_month": "June"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Jennifer", "eventtype": "boughtCodingCourse", "specifics": {"platform":"Coursera", "price": "50$"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Jennifer", "eventtype": "boughtCodingCourse", "specifics": {"platform":"Coursera", "price": "50$"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Chima", "eventtype": "subscribedToTV", "specifics": {"channel":"Disney", "for_month": "December"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Steve", "eventtype": "payingDues", "specifics": {"what":"light bills", "for_month": "June"}}' http://localhost:80/api/v1/submitevent &
curl -X POST -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoidXNlZnVsVXNlcjMifQ.7VsYcrhAHt0rsEoaW1zi9gei4IzaZcHKiCeow_A7ckg" -d '{"customer": "Jennifer", "eventtype": "boughtCodingCourse", "specifics": {"platform":"Coursera", "price": "50$"}}' http://localhost:80/api/v1/submitevent
