version: '3.8'
services:
  auditlogcustomerservice:
    build: ./auditlogcustomerservice
    command: ["go", "run", "main.go"]
    ports:
        - "4000:4000"
    depends_on: 
      # mongodb:
      #   condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   ports:
  #     - 27017:27017
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 20s
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #   depends_on:
  #     - mongodb
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    # volumes:
    #   - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin4
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    depends_on:
      - auditlogcustomerservice
  # web:
  #   restart: always
  #   build: ./web
  #   expose:
  #     - "8000"
  #   links:
  #     - postgres:postgres
  #   volumes:
  #     - /usr/src/flask-app/static
  #   env_file: .env
  #   command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /www/static
  #   volumes_from:
  #     - web
  #   links:
  #     - web:web